feat: remove `@synhaptein` fork from falcor-http-datasource
Mixgenius/Falcor-HTTP-WS-DataSource pull request #1
Opened 2017-07-04 17:40 UTC by ardeois

This was used to have dynamic headers, but this could be handled by
client directly. If you want dynamic headers, you could have an object
with dynamic properties.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty for more details

2017-07-04 17:42 UTC, ardeois commented
This is a breaking change!

2017-07-05 08:36 UTC, ludovicthomas reviewed
Nice work! LGTM. Not sure we had unit tests on that?

2017-07-05 14:30 UTC, ardeois commented
No we don't unfortunately

2017-08-01 19:19 UTC, ardeois commented
@synhaptein @ludovicthomas Version updated, ready to merge and publish a new major version

2017-08-02 09:40 UTC, ludovicthomas commented
I just checked the diff, and it's ok for the dynamic headers, but we are loosing the 'status' property on failed that was retrieved from an existing fork (see https://github.com/Netflix/falcor-http-datasource/compare/master...ajoslin:status-code-build).

For more details on our current diff with master, please check https://github.com/Netflix/falcor-http-datasource/compare/master...Mixgenius:landr_custom.

2017-08-02 13:10 UTC, synhaptein approved these changes
LGTM

2017-08-02 13:20 UTC, ardeois commented
Oh right good catch. This seems to be related to a discussion with phil yesterday, where removing falcor-router fork means we'll loose the status as well (for GET).
Maybe it would be better if we start by this (only if we find a creative alternative without forking)?

2017-08-02 13:22 UTC, synhaptein commented
arfff... https://github.com/Netflix/falcor-http-datasource/pull/33 has never been merged :/

2017-08-02 13:24 UTC, synhaptein requested changes
Thx to @ludovicthomas, I totally missed the merged I did from a PR still pending on the netflix repo :/ sorry for that

2017-08-08 15:42 UTC, ardeois commented
Closing this PR until I find a solution for this

2017-08-08 15:42 UTC, closed without merging